CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Businesses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "BusinessType" text NOT NULL,
    "Address" text NOT NULL,
    "Phone" text NOT NULL,
    "TaxNumber" text NOT NULL,
    CONSTRAINT "PK_Businesses" PRIMARY KEY ("Id")
);

CREATE TABLE "Chapters" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderIndex" integer NOT NULL,
    "Language" text NOT NULL,
    "Label" text NOT NULL,
    "Concept" text NOT NULL,
    "StoryHtml" text NOT NULL,
    "CodeHtml" text NOT NULL,
    "QuizPrompt" text NOT NULL,
    "OkFeedback" text NOT NULL,
    "BadFeedback" text NOT NULL,
    CONSTRAINT "PK_Chapters" PRIMARY KEY ("Id")
);

CREATE TABLE "GameSessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SessionKey" text NOT NULL,
    "PlayerName" text NOT NULL,
    "Language" text NOT NULL,
    "CurrentChapterIndex" integer NOT NULL,
    "Score" integer NOT NULL,
    "CorrectAnswers" integer NOT NULL,
    "IsComplete" boolean NOT NULL,
    "StartedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    CONSTRAINT "PK_GameSessions" PRIMARY KEY ("Id")
);

CREATE TABLE "LeaderboardEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerName" text NOT NULL,
    "Score" integer NOT NULL,
    "CorrectAnswers" integer NOT NULL,
    "Rank" text NOT NULL,
    "AchievedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LeaderboardEntries" PRIMARY KEY ("Id")
);

CREATE TABLE "PosStaff" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BusinessId" integer NOT NULL,
    "FullName" text NOT NULL,
    "Role" text NOT NULL,
    "PinCode" text NOT NULL,
    CONSTRAINT "PK_PosStaff" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PosStaff_Businesses_BusinessId" FOREIGN KEY ("BusinessId") REFERENCES "Businesses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PosSystems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BusinessId" integer NOT NULL,
    "Version" text NOT NULL,
    "SystemType" text NOT NULL,
    "FiscalPrinterEnabled" boolean NOT NULL,
    "Theme" text NOT NULL,
    "InstalledAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PosSystems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PosSystems_Businesses_BusinessId" FOREIGN KEY ("BusinessId") REFERENCES "Businesses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Choices" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ChapterId" integer NOT NULL,
    "Text" text NOT NULL,
    "IsCorrect" boolean NOT NULL,
    "OrderIndex" integer NOT NULL,
    CONSTRAINT "PK_Choices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Choices_Chapters_ChapterId" FOREIGN KEY ("ChapterId") REFERENCES "Chapters" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AnswerRecords" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GameSessionId" integer NOT NULL,
    "ChapterId" integer NOT NULL,
    "ChosenChoiceId" integer NOT NULL,
    "WasCorrect" boolean NOT NULL,
    "AnsweredAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AnswerRecords" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AnswerRecords_GameSessions_GameSessionId" FOREIGN KEY ("GameSessionId") REFERENCES "GameSessions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "POSOrders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PosSystemId" integer NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "OrderDate" timestamp with time zone NOT NULL,
    "Status" text NOT NULL,
    CONSTRAINT "PK_POSOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_POSOrders_PosSystems_PosSystemId" FOREIGN KEY ("PosSystemId") REFERENCES "PosSystems" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ProductItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Barcode" text NOT NULL,
    "Name" text NOT NULL,
    "Price" numeric NOT NULL,
    "PosSystemId" integer NOT NULL,
    "Category" text NOT NULL,
    CONSTRAINT "PK_ProductItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductItems_PosSystems_PosSystemId" FOREIGN KEY ("PosSystemId") REFERENCES "PosSystems" ("Id") ON DELETE CASCADE
);

CREATE TABLE "InventoryMovements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductItemId" integer NOT NULL,
    "QuantityChanged" integer NOT NULL,
    "Reason" text NOT NULL,
    "MovementDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InventoryMovements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InventoryMovements_ProductItems_ProductItemId" FOREIGN KEY ("ProductItemId") REFERENCES "ProductItems" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AnswerRecords_GameSessionId" ON "AnswerRecords" ("GameSessionId");

CREATE INDEX "IX_Choices_ChapterId" ON "Choices" ("ChapterId");

CREATE INDEX "IX_GameSessions_SessionKey" ON "GameSessions" ("SessionKey");

CREATE INDEX "IX_InventoryMovements_ProductItemId" ON "InventoryMovements" ("ProductItemId");

CREATE INDEX "IX_POSOrders_PosSystemId" ON "POSOrders" ("PosSystemId");

CREATE INDEX "IX_PosStaff_BusinessId" ON "PosStaff" ("BusinessId");

CREATE INDEX "IX_PosSystems_BusinessId" ON "PosSystems" ("BusinessId");

CREATE INDEX "IX_ProductItems_PosSystemId" ON "ProductItems" ("PosSystemId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260410082759_InitialCreate', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "GameSessions" ADD "GameType" text NOT NULL DEFAULT '';

ALTER TABLE "Chapters" ADD "GameType" text NOT NULL DEFAULT '';

CREATE TABLE "Customers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text NOT NULL,
    "LoyaltyPoints" integer NOT NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
);

CREATE TABLE "Vendors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "ContactPerson" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text NOT NULL,
    CONSTRAINT "PK_Vendors" PRIMARY KEY ("Id")
);

CREATE TABLE "PurchaseOrders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VendorId" integer NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "OrderDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PurchaseOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PurchaseOrders_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_PurchaseOrders_VendorId" ON "PurchaseOrders" ("VendorId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260410090132_AddGameType', '8.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderNumber" character varying(20) NOT NULL,
    "CustomerName" character varying(200) NOT NULL,
    "CustomerEmail" character varying(200),
    "CustomerPhone" character varying(50),
    "DeliveryAddress" character varying(500),
    "Notes" character varying(1000),
    "Status" integer NOT NULL,
    "PaymentMethod" integer NOT NULL,
    "SubTotal" numeric(10,2) NOT NULL,
    "DeliveryFee" numeric(10,2) NOT NULL,
    "TotalAmount" numeric(10,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id")
);

CREATE TABLE "ProductCategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Description" character varying(500),
    "ImageUrl" character varying(500),
    "SortOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_ProductCategories" PRIMARY KEY ("Id")
);

CREATE TABLE "OrderItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "ProductName" character varying(250) NOT NULL,
    "ProductImageUrl" character varying(500),
    "Quantity" numeric(10,2) NOT NULL,
    "UnitPrice" numeric(10,2) NOT NULL,
    "TotalPrice" numeric(10,2) NOT NULL,
    CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Barcode" character varying(50),
    "Name" character varying(250) NOT NULL,
    "Description" character varying(2000),
    "Price" numeric(10,2) NOT NULL,
    "SalePrice" numeric(10,2),
    "CategoryId" integer,
    "CategoryName" character varying(150),
    "Brand" character varying(100),
    "Unit" character varying(20),
    "StockQuantity" numeric(10,2) NOT NULL,
    "ImageUrl" character varying(500),
    "IsActive" boolean NOT NULL,
    "IsFeatured" boolean NOT NULL,
    "VatRate" numeric NOT NULL,
    "PosArticleId" bigint,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_ProductCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "ProductCategories" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");

CREATE UNIQUE INDEX "IX_Orders_OrderNumber" ON "Orders" ("OrderNumber");

CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");

CREATE INDEX "IX_Products_IsActive" ON "Products" ("IsActive");

CREATE INDEX "IX_Products_Name" ON "Products" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260429090053_AddEcommerceSchema', '8.0.11');

COMMIT;

